server:
  port: 8080
  servlet:
    context-path: /api
  
spring:
  application:
    name: smart-home-voice-assistant
  datasource:
    url: jdbc:h2:mem:smarthome;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  
logging:
  level:
    com.smarthome: INFO
    org.springframework: INFO
  charset:
    console: UTF-8
    file: UTF-8
    
# NLP服务配置
nlp:
  service:
    baseurl: http://localhost:8010
    
# 音频处理配置
voice:
  # 选择处理器类型: real(使用实际的Python NLP服务)
  processor:
    type: real
  module:
    path: ./nlp_service
  audio:
    silence-threshold: 0.01
    silence-duration: 1.0
    min-speech-duration: 0.5
  stt:
    engine-type: dolphin
  nlu:
    engine-type: fine_tuned_bert 